//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Literals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Literals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fantasy.Shared.Resources.Literals", typeof(Literals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Team.
        /// </summary>
        public static string AppAddTeam {
            get {
                return ResourceManager.GetString("AppAddTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Team to Tournament.
        /// </summary>
        public static string AppAddTeamToTournament {
            get {
                return ResourceManager.GetString("AppAddTeamToTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin users group.
        /// </summary>
        public static string AppAdminUsersGroup {
            get {
                return ResourceManager.GetString("AppAdminUsersGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling Code.
        /// </summary>
        public static string AppCallingCode {
            get {
                return ResourceManager.GetString("AppCallingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Match.
        /// </summary>
        public static string AppCloseMatch {
            get {
                return ResourceManager.GetString("AppCloseMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the match {0} Vs. {1}?.
        /// </summary>
        public static string AppCloseMatchConfirmMessage {
            get {
                return ResourceManager.GetString("AppCloseMatchConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Match.
        /// </summary>
        public static string AppCloseMatchTitle {
            get {
                return ResourceManager.GetString("AppCloseMatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string AppCode {
            get {
                return ResourceManager.GetString("AppCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string AppCountries {
            get {
                return ResourceManager.GetString("AppCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string AppCountry {
            get {
                return ResourceManager.GetString("AppCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Points.
        /// </summary>
        public static string AppDoublePoints {
            get {
                return ResourceManager.GetString("AppDoublePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Points Match.
        /// </summary>
        public static string AppDoublePointsMatchMessage {
            get {
                return ResourceManager.GetString("AppDoublePointsMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals Local.
        /// </summary>
        public static string AppGoalsLocal {
            get {
                return ResourceManager.GetString("AppGoalsLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a value greater than or equal to zero in local goals..
        /// </summary>
        public static string AppGoalsLocalError {
            get {
                return ResourceManager.GetString("AppGoalsLocalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals Visitor.
        /// </summary>
        public static string AppGoalsVisitor {
            get {
                return ResourceManager.GetString("AppGoalsVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a value greater than or equal to zero in visitor goals..
        /// </summary>
        public static string AppGoalsVisitorError {
            get {
                return ResourceManager.GetString("AppGoalsVisitorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string AppGroup {
            get {
                return ResourceManager.GetString("AppGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group: {0} has been created, with code: {1}, Invitation URL {2} has been copied to clipboard, please share it with your friends to join your group..
        /// </summary>
        public static string AppGroupCreated {
            get {
                return ResourceManager.GetString("AppGroupCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Details.
        /// </summary>
        public static string AppGroupDetails {
            get {
                return ResourceManager.GetString("AppGroupDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string AppGroups {
            get {
                return ResourceManager.GetString("AppGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group invitation link {0} copied to clipboard. Share it with your friends to join the group..
        /// </summary>
        public static string AppInvitationURLCopied {
            get {
                return ResourceManager.GetString("AppInvitationURLCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join an existing group.
        /// </summary>
        public static string AppJoinExistingGroup {
            get {
                return ResourceManager.GetString("AppJoinExistingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Group.
        /// </summary>
        public static string AppJoinGroup {
            get {
                return ResourceManager.GetString("AppJoinGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string AppLocal {
            get {
                return ResourceManager.GetString("AppLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match.
        /// </summary>
        public static string AppMatch {
            get {
                return ResourceManager.GetString("AppMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Active.
        /// </summary>
        public static string AppMatchActive {
            get {
                return ResourceManager.GetString("AppMatchActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string AppMatches {
            get {
                return ResourceManager.GetString("AppMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Inactive.
        /// </summary>
        public static string AppMatchInactive {
            get {
                return ResourceManager.GetString("AppMatchInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string AppMembers {
            get {
                return ResourceManager.GetString("AppMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a local team..
        /// </summary>
        public static string AppMustSelectLocalTeam {
            get {
                return ResourceManager.GetString("AppMustSelectLocalTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a visitor team..
        /// </summary>
        public static string AppMustSelectVisitorTeam {
            get {
                return ResourceManager.GetString("AppMustSelectVisitorTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Groups.
        /// </summary>
        public static string AppMyGroups {
            get {
                return ResourceManager.GetString("AppMyGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not part of any group. You can join a group using the URL or code shared by the group administrator, or you can view the available groups on the homepage and then ask the administrator to activate you so you can enter your predictions. You can also create your own group of friends..
        /// </summary>
        public static string AppNoGroups {
            get {
                return ResourceManager.GetString("AppNoGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string AppPoints {
            get {
                return ResourceManager.GetString("AppPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Match to Tournament.
        /// </summary>
        public static string AppPollaAddMatchToTournament {
            get {
                return ResourceManager.GetString("AppPollaAddMatchToTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        public static string AppPositions {
            get {
                return ResourceManager.GetString("AppPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PredictedScore.
        /// </summary>
        public static string AppPredictedScore {
            get {
                return ResourceManager.GetString("AppPredictedScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction.
        /// </summary>
        public static string AppPrediction {
            get {
                return ResourceManager.GetString("AppPrediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictions.
        /// </summary>
        public static string AppPredictions {
            get {
                return ResourceManager.GetString("AppPredictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictions Balance.
        /// </summary>
        public static string AppPredictionsBalance {
            get {
                return ResourceManager.GetString("AppPredictionsBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Score.
        /// </summary>
        public static string AppRealScore {
            get {
                return ResourceManager.GetString("AppRealScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-open match.
        /// </summary>
        public static string AppReOpenMatch {
            get {
                return ResourceManager.GetString("AppReOpenMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to re-open the {0}: {1}?.
        /// </summary>
        public static string AppReOpenMatchConfirm {
            get {
                return ResourceManager.GetString("AppReOpenMatchConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match has been reopened.
        /// </summary>
        public static string AppReOpenMatchMessage {
            get {
                return ResourceManager.GetString("AppReOpenMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select a option--.
        /// </summary>
        public static string AppSelect {
            get {
                return ResourceManager.GetString("AppSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select a Country --.
        /// </summary>
        public static string AppSelectACountry {
            get {
                return ResourceManager.GetString("AppSelectACountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select a Tournament --.
        /// </summary>
        public static string AppSelectATournament {
            get {
                return ResourceManager.GetString("AppSelectATournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Points Match.
        /// </summary>
        public static string AppSinglePointsMatchMessage {
            get {
                return ResourceManager.GetString("AppSinglePointsMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string AppTeam {
            get {
                return ResourceManager.GetString("AppTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string AppTeams {
            get {
                return ResourceManager.GetString("AppTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament.
        /// </summary>
        public static string AppTournament {
            get {
                return ResourceManager.GetString("AppTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tournament is active.
        /// </summary>
        public static string AppTournamentActive {
            get {
                return ResourceManager.GetString("AppTournamentActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tournament is inactive.
        /// </summary>
        public static string AppTournamentInactive {
            get {
                return ResourceManager.GetString("AppTournamentInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournaments.
        /// </summary>
        public static string AppTournaments {
            get {
                return ResourceManager.GetString("AppTournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor.
        /// </summary>
        public static string AppVisitor {
            get {
                return ResourceManager.GetString("AppVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch.
        /// </summary>
        public static string AppWatch {
            get {
                return ResourceManager.GetString("AppWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Predictions.
        /// </summary>
        public static string AppWatchPredictions {
            get {
                return ResourceManager.GetString("AppWatchPredictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfa2 Code.
        /// </summary>
        public static string CountryAlfa2Code {
            get {
                return ResourceManager.GetString("CountryAlfa2Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfa3 Code.
        /// </summary>
        public static string CountryAlfa3Code {
            get {
                return ResourceManager.GetString("CountryAlfa3Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling Code.
        /// </summary>
        public static string CountryCallingCode {
            get {
                return ResourceManager.GetString("CountryCallingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Currency.
        /// </summary>
        public static string CountryDefaultCurrencyCode {
            get {
                return ResourceManager.GetString("CountryDefaultCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID.
        /// </summary>
        public static string CountryGuid {
            get {
                return ResourceManager.GetString("CountryGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO name.
        /// </summary>
        public static string CountryISOname {
            get {
                return ResourceManager.GetString("CountryISOname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string CountryTenant {
            get {
                return ResourceManager.GetString("CountryTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string CurrencyCode {
            get {
                return ResourceManager.GetString("CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID.
        /// </summary>
        public static string CurrencyGuid {
            get {
                return ResourceManager.GetString("CurrencyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string CurrencyTenant {
            get {
                return ResourceManager.GetString("CurrencyTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string CurrencyValue {
            get {
                return ResourceManager.GetString("CurrencyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprices.
        /// </summary>
        public static string Enterprices {
            get {
                return ResourceManager.GetString("Enterprices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string EnterpriseTenant {
            get {
                return ResourceManager.GetString("EnterpriseTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found..
        /// </summary>
        public static string ERR001 {
            get {
                return ResourceManager.GetString("ERR001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be deleted because it has related records..
        /// </summary>
        public static string ERR002 {
            get {
                return ResourceManager.GetString("ERR002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record you are trying to create already exists..
        /// </summary>
        public static string ERR003 {
            get {
                return ResourceManager.GetString("ERR003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country Id is not valid..
        /// </summary>
        public static string ERR004 {
            get {
                return ResourceManager.GetString("ERR004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team Id is not valid..
        /// </summary>
        public static string ERR005 {
            get {
                return ResourceManager.GetString("ERR005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email or password..
        /// </summary>
        public static string ERR006 {
            get {
                return ResourceManager.GetString("ERR006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded the maximum number of attempts, your account is blocked, please try again in 5 minutes..
        /// </summary>
        public static string ERR007 {
            get {
                return ResourceManager.GetString("ERR007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has not been enabled, you must follow the instructions in the email sent to enable the user..
        /// </summary>
        public static string ERR008 {
            get {
                return ResourceManager.GetString("ERR008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tournament Id is not valid..
        /// </summary>
        public static string ERR009 {
            get {
                return ResourceManager.GetString("ERR009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local Id is not valid..
        /// </summary>
        public static string ERR010 {
            get {
                return ResourceManager.GetString("ERR010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The visitor Id is not valid..
        /// </summary>
        public static string ERR011 {
            get {
                return ResourceManager.GetString("ERR011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match Id is not valid..
        /// </summary>
        public static string ERR012 {
            get {
                return ResourceManager.GetString("ERR012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user Id is not valid..
        /// </summary>
        public static string ERR013 {
            get {
                return ResourceManager.GetString("ERR013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group Id is not valid..
        /// </summary>
        public static string ERR014 {
            get {
                return ResourceManager.GetString("ERR014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user group is not valid..
        /// </summary>
        public static string ERR015 {
            get {
                return ResourceManager.GetString("ERR015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prediction Id is not valid..
        /// </summary>
        public static string ERR016 {
            get {
                return ResourceManager.GetString("ERR016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group code is not valid..
        /// </summary>
        public static string ERR017 {
            get {
                return ResourceManager.GetString("ERR017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This match is no longer open to predictions..
        /// </summary>
        public static string ERR018 {
            get {
                return ResourceManager.GetString("ERR018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string IUAbout {
            get {
                return ResourceManager.GetString("IUAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;p&gt;A system where different groups of friends can make predictions about football tournaments. In Colombia, it’s called “Polla”; in Argentina, “Prode”; and in the United States, “Fantasy.” The idea is that any number of football tournaments, such as the Copa América, the World Cup, the Euro Cup, the Champions League, or the Colombian League, among others, can be registered. Groups of friends will be able to form their own “Pollas” and make predictions about the matches. Once the matches are completed an [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IUAboutText {
            get {
                return ResourceManager.GetString("IUAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string IUActions {
            get {
                return ResourceManager.GetString("IUActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string IUActivate {
            get {
                return ResourceManager.GetString("IUActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string IUActive {
            get {
                return ResourceManager.GetString("IUActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string IUAdd {
            get {
                return ResourceManager.GetString("IUAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string IUAll {
            get {
                return ResourceManager.GetString("IUAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string IUAuthor {
            get {
                return ResourceManager.GetString("IUAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorizing....
        /// </summary>
        public static string IUAuthorizing {
            get {
                return ResourceManager.GetString("IUAuthorizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string IUCancel {
            get {
                return ResourceManager.GetString("IUCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        public static string IUClean {
            get {
                return ResourceManager.GetString("IUClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string IUCode {
            get {
                return ResourceManager.GetString("IUCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string IUConfirmation {
            get {
                return ResourceManager.GetString("IUConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string IUCreate {
            get {
                return ResourceManager.GetString("IUCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string IUDate {
            get {
                return ResourceManager.GetString("IUDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string IUDeactivate {
            get {
                return ResourceManager.GetString("IUDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string IUDelete {
            get {
                return ResourceManager.GetString("IUDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the {0}: {1}?.
        /// </summary>
        public static string IUDeleteConfirm {
            get {
                return ResourceManager.GetString("IUDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string IUEdit {
            get {
                return ResourceManager.GetString("IUEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string IUEnglish {
            get {
                return ResourceManager.GetString("IUEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string IUError {
            get {
                return ResourceManager.GetString("IUError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string IUFilter {
            get {
                return ResourceManager.GetString("IUFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string IUHome {
            get {
                return ResourceManager.GetString("IUHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string IUImage {
            get {
                return ResourceManager.GetString("IUImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image is rectangular.
        /// </summary>
        public static string IUImageIsRectangular {
            get {
                return ResourceManager.GetString("IUImageIsRectangular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image is square.
        /// </summary>
        public static string IUImageIsSquare {
            get {
                return ResourceManager.GetString("IUImageIsSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string IUInactive {
            get {
                return ResourceManager.GetString("IUInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IUIsActive {
            get {
                return ResourceManager.GetString("IUIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Image Square?.
        /// </summary>
        public static string IUIsImageSquare {
            get {
                return ResourceManager.GetString("IUIsImageSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to leave the page and lose your changes?.
        /// </summary>
        public static string IULeaveAndLoseChanges {
            get {
                return ResourceManager.GetString("IULeaveAndLoseChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must be between {2} and {1} characters..
        /// </summary>
        public static string IULengthField {
            get {
                return ResourceManager.GetString("IULengthField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} cannot be longer than {1} characters..
        /// </summary>
        public static string IUMaxLength {
            get {
                return ResourceManager.GetString("IUMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must have at least {1} characters..
        /// </summary>
        public static string IUMinLength {
            get {
                return ResourceManager.GetString("IUMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string IUNew {
            get {
                return ResourceManager.GetString("IUNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string IUNo {
            get {
                return ResourceManager.GetString("IUNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records to show....
        /// </summary>
        public static string IUNoRecords {
            get {
                return ResourceManager.GetString("IUNoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string IUNotFound {
            get {
                return ResourceManager.GetString("IUNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there is nothing on this route..
        /// </summary>
        public static string IUNothingInRoute {
            get {
                return ResourceManager.GetString("IUNothingInRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string IUPleaseWait {
            get {
                return ResourceManager.GetString("IUPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record created successfully..
        /// </summary>
        public static string IURecordCreatedOk {
            get {
                return ResourceManager.GetString("IURecordCreatedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted successfully..
        /// </summary>
        public static string IURecordDeletedOk {
            get {
                return ResourceManager.GetString("IURecordDeletedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record saved successfully..
        /// </summary>
        public static string IURecordSavedOk {
            get {
                return ResourceManager.GetString("IURecordSavedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records Number:.
        /// </summary>
        public static string IURecordsNumber {
            get {
                return ResourceManager.GetString("IURecordsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangular.
        /// </summary>
        public static string IURectangular {
            get {
                return ResourceManager.GetString("IURectangular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string IURemarks {
            get {
                return ResourceManager.GetString("IURemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is required..
        /// </summary>
        public static string IURequiredField {
            get {
                return ResourceManager.GetString("IURequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string IUReturn {
            get {
                return ResourceManager.GetString("IUReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string IUSaveChanges {
            get {
                return ResourceManager.GetString("IUSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string IUSearch {
            get {
                return ResourceManager.GetString("IUSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Date....
        /// </summary>
        public static string IUSelectDate {
            get {
                return ResourceManager.GetString("IUSelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a File… .
        /// </summary>
        public static string IUSelectFile {
            get {
                return ResourceManager.GetString("IUSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Time....
        /// </summary>
        public static string IUSelectTime {
            get {
                return ResourceManager.GetString("IUSelectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string IUSend {
            get {
                return ResourceManager.GetString("IUSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string IUSpanish {
            get {
                return ResourceManager.GetString("IUSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        public static string IUSquare {
            get {
                return ResourceManager.GetString("IUSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integral construction .
        /// </summary>
        public static string IUSubtitle {
            get {
                return ResourceManager.GetString("IUSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlBIM.
        /// </summary>
        public static string IUTitle {
            get {
                return ResourceManager.GetString("IUTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string IUYes {
            get {
                return ResourceManager.GetString("IUYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string.
        /// </summary>
        public static string SubscriptionConnectionString {
            get {
                return ResourceManager.GetString("SubscriptionConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string SubscriptionCreationDate {
            get {
                return ResourceManager.GetString("SubscriptionCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk space.
        /// </summary>
        public static string SubscriptionDiskSpace {
            get {
                return ResourceManager.GetString("SubscriptionDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration .
        /// </summary>
        public static string SubscriptionExpirationDate {
            get {
                return ResourceManager.GetString("SubscriptionExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max electronic docs.
        /// </summary>
        public static string SubscriptionMaxElectronicsDocs {
            get {
                return ResourceManager.GetString("SubscriptionMaxElectronicsDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Enterprises.
        /// </summary>
        public static string SubscriptionMaxEnterprises {
            get {
                return ResourceManager.GetString("SubscriptionMaxEnterprises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Space.
        /// </summary>
        public static string SubscriptionMaxSpace {
            get {
                return ResourceManager.GetString("SubscriptionMaxSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Users.
        /// </summary>
        public static string SubscriptionMaxUsers {
            get {
                return ResourceManager.GetString("SubscriptionMaxUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SubscriptionName {
            get {
                return ResourceManager.GetString("SubscriptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string Subscriptions {
            get {
                return ResourceManager.GetString("Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string SubscriptionTenant {
            get {
                return ResourceManager.GetString("SubscriptionTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string Tenant {
            get {
                return ResourceManager.GetString("Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string TenantCode {
            get {
                return ResourceManager.GetString("TenantCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection String.
        /// </summary>
        public static string TenantConnectionString {
            get {
                return ResourceManager.GetString("TenantConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string TenantIsActive {
            get {
                return ResourceManager.GetString("TenantIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TenantName {
            get {
                return ResourceManager.GetString("TenantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenants.
        /// </summary>
        public static string Tenants {
            get {
                return ResourceManager.GetString("Tenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Path.
        /// </summary>
        public static string TenantStoragePath {
            get {
                return ResourceManager.GetString("TenantStoragePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User added to the group. The user can now enter and enter their predictions..
        /// </summary>
        public static string UserAddedToGroupOk {
            get {
                return ResourceManager.GetString("UserAddedToGroupOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string UserAdmin {
            get {
                return ResourceManager.GetString("UserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Registration.
        /// </summary>
        public static string UserAdminRegister {
            get {
                return ResourceManager.GetString("UserAdminRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string UserChangePassword {
            get {
                return ResourceManager.GetString("UserChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string UserConfirmed {
            get {
                return ResourceManager.GetString("UserConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email, you can now log in to the system..
        /// </summary>
        public static string UserConfirmedEmailMessage {
            get {
                return ResourceManager.GetString("UserConfirmedEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmation.
        /// </summary>
        public static string UserConfirmEmail {
            get {
                return ResourceManager.GetString("UserConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the button to confirm your account..
        /// </summary>
        public static string UserConfirmEmailMessage {
            get {
                return ResourceManager.GetString("UserConfirmEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To join the group: {0}, click the button..
        /// </summary>
        public static string UserConfirmGroupMessage {
            get {
                return ResourceManager.GetString("UserConfirmGroupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy invitation.
        /// </summary>
        public static string UserCopyInvitationURLTitle {
            get {
                return ResourceManager.GetString("UserCopyInvitationURLTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string UserCurrentPassword {
            get {
                return ResourceManager.GetString("UserCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User Profile.
        /// </summary>
        public static string UserEditUserProfile {
            get {
                return ResourceManager.GetString("UserEditUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email you entered already exists..
        /// </summary>
        public static string UserEmailAlreadyExists {
            get {
                return ResourceManager.GetString("UserEmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string UserFirstName {
            get {
                return ResourceManager.GetString("UserFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you forgotten your password?.
        /// </summary>
        public static string UserForgottenYourPassword {
            get {
                return ResourceManager.GetString("UserForgottenYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string UserHello {
            get {
                return ResourceManager.GetString("UserHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string UserImage {
            get {
                return ResourceManager.GetString("UserImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string UserLastName {
            get {
                return ResourceManager.GetString("UserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string UserLogout {
            get {
                return ResourceManager.GetString("UserLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        public static string UserLogoutConfirm {
            get {
                return ResourceManager.GetString("UserLogoutConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you log out, you will need to log back in to access your account..
        /// </summary>
        public static string UserLogoutMessage {
            get {
                return ResourceManager.GetString("UserLogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail forwarding.
        /// </summary>
        public static string UserMailForwarding {
            get {
                return ResourceManager.GetString("UserMailForwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string UserNewPassword {
            get {
                return ResourceManager.GetString("UserNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as new user.
        /// </summary>
        public static string UserNewRegister {
            get {
                return ResourceManager.GetString("UserNewRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to view this content....
        /// </summary>
        public static string UserNotAuthorized {
            get {
                return ResourceManager.GetString("UserNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a user yet? Register here.
        /// </summary>
        public static string UserNotUserYet {
            get {
                return ResourceManager.GetString("UserNotUserYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation are not the same..
        /// </summary>
        public static string UserPasswordAndConfirmationDifferent {
            get {
                return ResourceManager.GetString("UserPasswordAndConfirmationDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed Successfully..
        /// </summary>
        public static string UserPasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("UserPasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirm.
        /// </summary>
        public static string UserPasswordConfirm {
            get {
                return ResourceManager.GetString("UserPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully, you can now log in with your new password..
        /// </summary>
        public static string UserPasswordRecoveredMessage {
            get {
                return ResourceManager.GetString("UserPasswordRecoveredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery.
        /// </summary>
        public static string UserPasswordRecovery {
            get {
                return ResourceManager.GetString("UserPasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string UserPhoneNumber {
            get {
                return ResourceManager.GetString("UserPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has been sent to you with instructions on how to recover your password..
        /// </summary>
        public static string UserRecoverPasswordMessage {
            get {
                return ResourceManager.GetString("UserRecoverPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Registration.
        /// </summary>
        public static string UserRegister {
            get {
                return ResourceManager.GetString("UserRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend account activation email.
        /// </summary>
        public static string UserResendAccountActivationEmail {
            get {
                return ResourceManager.GetString("UserResendAccountActivationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been created successfully. An email has been sent to you with instructions on how to activate your account..
        /// </summary>
        public static string UserSendEmailConfirmationMessage {
            get {
                return ResourceManager.GetString("UserSendEmailConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid email..
        /// </summary>
        public static string UserValidEmail {
            get {
                return ResourceManager.GetString("UserValidEmail", resourceCulture);
            }
        }
    }
}
